spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/caraliu_library?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456